// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.ecommerce.website.grpc;

public final class Customer {
  private Customer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 mobile = 1;</code>
     */
    long getMobile();
  }
  /**
   * Protobuf type {@code CustomerRequest}
   */
  public  static final class CustomerRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CustomerRequest)
      CustomerRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerRequest.newBuilder() to construct.
    private CustomerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerRequest() {
      mobile_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              mobile_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.website.grpc.Customer.internal_static_CustomerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.website.grpc.Customer.internal_static_CustomerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.website.grpc.Customer.CustomerRequest.class, com.ecommerce.website.grpc.Customer.CustomerRequest.Builder.class);
    }

    public static final int MOBILE_FIELD_NUMBER = 1;
    private long mobile_;
    /**
     * <code>int64 mobile = 1;</code>
     */
    public long getMobile() {
      return mobile_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mobile_ != 0L) {
        output.writeInt64(1, mobile_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mobile_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, mobile_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ecommerce.website.grpc.Customer.CustomerRequest)) {
        return super.equals(obj);
      }
      com.ecommerce.website.grpc.Customer.CustomerRequest other = (com.ecommerce.website.grpc.Customer.CustomerRequest) obj;

      boolean result = true;
      result = result && (getMobile()
          == other.getMobile());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMobile());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ecommerce.website.grpc.Customer.CustomerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomerRequest)
        com.ecommerce.website.grpc.Customer.CustomerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ecommerce.website.grpc.Customer.CustomerRequest.class, com.ecommerce.website.grpc.Customer.CustomerRequest.Builder.class);
      }

      // Construct using com.ecommerce.website.grpc.Customer.CustomerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mobile_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRequest_descriptor;
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRequest getDefaultInstanceForType() {
        return com.ecommerce.website.grpc.Customer.CustomerRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRequest build() {
        com.ecommerce.website.grpc.Customer.CustomerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRequest buildPartial() {
        com.ecommerce.website.grpc.Customer.CustomerRequest result = new com.ecommerce.website.grpc.Customer.CustomerRequest(this);
        result.mobile_ = mobile_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ecommerce.website.grpc.Customer.CustomerRequest) {
          return mergeFrom((com.ecommerce.website.grpc.Customer.CustomerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ecommerce.website.grpc.Customer.CustomerRequest other) {
        if (other == com.ecommerce.website.grpc.Customer.CustomerRequest.getDefaultInstance()) return this;
        if (other.getMobile() != 0L) {
          setMobile(other.getMobile());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ecommerce.website.grpc.Customer.CustomerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ecommerce.website.grpc.Customer.CustomerRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long mobile_ ;
      /**
       * <code>int64 mobile = 1;</code>
       */
      public long getMobile() {
        return mobile_;
      }
      /**
       * <code>int64 mobile = 1;</code>
       */
      public Builder setMobile(long value) {
        
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mobile = 1;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CustomerRequest)
    }

    // @@protoc_insertion_point(class_scope:CustomerRequest)
    private static final com.ecommerce.website.grpc.Customer.CustomerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ecommerce.website.grpc.Customer.CustomerRequest();
    }

    public static com.ecommerce.website.grpc.Customer.CustomerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerRequest>
        PARSER = new com.google.protobuf.AbstractParser<CustomerRequest>() {
      @java.lang.Override
      public CustomerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ecommerce.website.grpc.Customer.CustomerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomerRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 customerId = 1;</code>
     */
    long getCustomerId();

    /**
     * <code>string firstName = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string mobile = 5;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>string mobile = 5;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>string address = 6;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 6;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string password = 7;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 7;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code CustomerRegister}
   */
  public  static final class CustomerRegister extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CustomerRegister)
      CustomerRegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerRegister.newBuilder() to construct.
    private CustomerRegister(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerRegister() {
      customerId_ = 0L;
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      mobile_ = "";
      address_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              customerId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.website.grpc.Customer.CustomerRegister.class, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder.class);
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 1;
    private long customerId_;
    /**
     * <code>int64 customerId = 1;</code>
     */
    public long getCustomerId() {
      return customerId_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 5;
    private volatile java.lang.Object mobile_;
    /**
     * <code>string mobile = 5;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 6;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 6;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 7;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 7;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (customerId_ != 0L) {
        output.writeInt64(1, customerId_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mobile_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, address_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (customerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, customerId_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mobile_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, address_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ecommerce.website.grpc.Customer.CustomerRegister)) {
        return super.equals(obj);
      }
      com.ecommerce.website.grpc.Customer.CustomerRegister other = (com.ecommerce.website.grpc.Customer.CustomerRegister) obj;

      boolean result = true;
      result = result && (getCustomerId()
          == other.getCustomerId());
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getMobile()
          .equals(other.getMobile());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerId());
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ecommerce.website.grpc.Customer.CustomerRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomerRegister)
        com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegister_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ecommerce.website.grpc.Customer.CustomerRegister.class, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder.class);
      }

      // Construct using com.ecommerce.website.grpc.Customer.CustomerRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        customerId_ = 0L;

        firstName_ = "";

        lastName_ = "";

        email_ = "";

        mobile_ = "";

        address_ = "";

        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegister_descriptor;
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRegister getDefaultInstanceForType() {
        return com.ecommerce.website.grpc.Customer.CustomerRegister.getDefaultInstance();
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRegister build() {
        com.ecommerce.website.grpc.Customer.CustomerRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRegister buildPartial() {
        com.ecommerce.website.grpc.Customer.CustomerRegister result = new com.ecommerce.website.grpc.Customer.CustomerRegister(this);
        result.customerId_ = customerId_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.email_ = email_;
        result.mobile_ = mobile_;
        result.address_ = address_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ecommerce.website.grpc.Customer.CustomerRegister) {
          return mergeFrom((com.ecommerce.website.grpc.Customer.CustomerRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ecommerce.website.grpc.Customer.CustomerRegister other) {
        if (other == com.ecommerce.website.grpc.Customer.CustomerRegister.getDefaultInstance()) return this;
        if (other.getCustomerId() != 0L) {
          setCustomerId(other.getCustomerId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ecommerce.website.grpc.Customer.CustomerRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ecommerce.website.grpc.Customer.CustomerRegister) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long customerId_ ;
      /**
       * <code>int64 customerId = 1;</code>
       */
      public long getCustomerId() {
        return customerId_;
      }
      /**
       * <code>int64 customerId = 1;</code>
       */
      public Builder setCustomerId(long value) {
        
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 customerId = 1;</code>
       */
      public Builder clearCustomerId() {
        
        customerId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>string mobile = 5;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobile = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile = 5;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 5;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 5;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 6;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 6;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 6;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 6;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 7;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 7;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 7;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 7;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CustomerRegister)
    }

    // @@protoc_insertion_point(class_scope:CustomerRegister)
    private static final com.ecommerce.website.grpc.Customer.CustomerRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ecommerce.website.grpc.Customer.CustomerRegister();
    }

    public static com.ecommerce.website.grpc.Customer.CustomerRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerRegister>
        PARSER = new com.google.protobuf.AbstractParser<CustomerRegister>() {
      @java.lang.Override
      public CustomerRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerRegister(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerRegister> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ecommerce.website.grpc.Customer.CustomerRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerRegisterResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomerRegisterResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    java.util.List<com.ecommerce.website.grpc.Customer.CustomerRegister> 
        getCustomerRegisterList();
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    com.ecommerce.website.grpc.Customer.CustomerRegister getCustomerRegister(int index);
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    int getCustomerRegisterCount();
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    java.util.List<? extends com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder> 
        getCustomerRegisterOrBuilderList();
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder getCustomerRegisterOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CustomerRegisterResponse}
   */
  public  static final class CustomerRegisterResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CustomerRegisterResponse)
      CustomerRegisterResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerRegisterResponse.newBuilder() to construct.
    private CustomerRegisterResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerRegisterResponse() {
      customerRegister_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerRegisterResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                customerRegister_ = new java.util.ArrayList<com.ecommerce.website.grpc.Customer.CustomerRegister>();
                mutable_bitField0_ |= 0x00000001;
              }
              customerRegister_.add(
                  input.readMessage(com.ecommerce.website.grpc.Customer.CustomerRegister.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          customerRegister_ = java.util.Collections.unmodifiableList(customerRegister_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegisterResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegisterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.class, com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.Builder.class);
    }

    public static final int CUSTOMERREGISTER_FIELD_NUMBER = 1;
    private java.util.List<com.ecommerce.website.grpc.Customer.CustomerRegister> customerRegister_;
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    public java.util.List<com.ecommerce.website.grpc.Customer.CustomerRegister> getCustomerRegisterList() {
      return customerRegister_;
    }
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    public java.util.List<? extends com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder> 
        getCustomerRegisterOrBuilderList() {
      return customerRegister_;
    }
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    public int getCustomerRegisterCount() {
      return customerRegister_.size();
    }
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    public com.ecommerce.website.grpc.Customer.CustomerRegister getCustomerRegister(int index) {
      return customerRegister_.get(index);
    }
    /**
     * <code>repeated .CustomerRegister customerRegister = 1;</code>
     */
    public com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder getCustomerRegisterOrBuilder(
        int index) {
      return customerRegister_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customerRegister_.size(); i++) {
        output.writeMessage(1, customerRegister_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customerRegister_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customerRegister_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ecommerce.website.grpc.Customer.CustomerRegisterResponse)) {
        return super.equals(obj);
      }
      com.ecommerce.website.grpc.Customer.CustomerRegisterResponse other = (com.ecommerce.website.grpc.Customer.CustomerRegisterResponse) obj;

      boolean result = true;
      result = result && getCustomerRegisterList()
          .equals(other.getCustomerRegisterList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomerRegisterCount() > 0) {
        hash = (37 * hash) + CUSTOMERREGISTER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerRegisterList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ecommerce.website.grpc.Customer.CustomerRegisterResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerRegisterResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomerRegisterResponse)
        com.ecommerce.website.grpc.Customer.CustomerRegisterResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegisterResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegisterResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.class, com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.Builder.class);
      }

      // Construct using com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCustomerRegisterFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (customerRegisterBuilder_ == null) {
          customerRegister_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          customerRegisterBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ecommerce.website.grpc.Customer.internal_static_CustomerRegisterResponse_descriptor;
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRegisterResponse getDefaultInstanceForType() {
        return com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRegisterResponse build() {
        com.ecommerce.website.grpc.Customer.CustomerRegisterResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ecommerce.website.grpc.Customer.CustomerRegisterResponse buildPartial() {
        com.ecommerce.website.grpc.Customer.CustomerRegisterResponse result = new com.ecommerce.website.grpc.Customer.CustomerRegisterResponse(this);
        int from_bitField0_ = bitField0_;
        if (customerRegisterBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            customerRegister_ = java.util.Collections.unmodifiableList(customerRegister_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customerRegister_ = customerRegister_;
        } else {
          result.customerRegister_ = customerRegisterBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ecommerce.website.grpc.Customer.CustomerRegisterResponse) {
          return mergeFrom((com.ecommerce.website.grpc.Customer.CustomerRegisterResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ecommerce.website.grpc.Customer.CustomerRegisterResponse other) {
        if (other == com.ecommerce.website.grpc.Customer.CustomerRegisterResponse.getDefaultInstance()) return this;
        if (customerRegisterBuilder_ == null) {
          if (!other.customerRegister_.isEmpty()) {
            if (customerRegister_.isEmpty()) {
              customerRegister_ = other.customerRegister_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomerRegisterIsMutable();
              customerRegister_.addAll(other.customerRegister_);
            }
            onChanged();
          }
        } else {
          if (!other.customerRegister_.isEmpty()) {
            if (customerRegisterBuilder_.isEmpty()) {
              customerRegisterBuilder_.dispose();
              customerRegisterBuilder_ = null;
              customerRegister_ = other.customerRegister_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customerRegisterBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomerRegisterFieldBuilder() : null;
            } else {
              customerRegisterBuilder_.addAllMessages(other.customerRegister_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ecommerce.website.grpc.Customer.CustomerRegisterResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ecommerce.website.grpc.Customer.CustomerRegisterResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ecommerce.website.grpc.Customer.CustomerRegister> customerRegister_ =
        java.util.Collections.emptyList();
      private void ensureCustomerRegisterIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          customerRegister_ = new java.util.ArrayList<com.ecommerce.website.grpc.Customer.CustomerRegister>(customerRegister_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ecommerce.website.grpc.Customer.CustomerRegister, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder, com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder> customerRegisterBuilder_;

      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public java.util.List<com.ecommerce.website.grpc.Customer.CustomerRegister> getCustomerRegisterList() {
        if (customerRegisterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customerRegister_);
        } else {
          return customerRegisterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public int getCustomerRegisterCount() {
        if (customerRegisterBuilder_ == null) {
          return customerRegister_.size();
        } else {
          return customerRegisterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public com.ecommerce.website.grpc.Customer.CustomerRegister getCustomerRegister(int index) {
        if (customerRegisterBuilder_ == null) {
          return customerRegister_.get(index);
        } else {
          return customerRegisterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder setCustomerRegister(
          int index, com.ecommerce.website.grpc.Customer.CustomerRegister value) {
        if (customerRegisterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerRegisterIsMutable();
          customerRegister_.set(index, value);
          onChanged();
        } else {
          customerRegisterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder setCustomerRegister(
          int index, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder builderForValue) {
        if (customerRegisterBuilder_ == null) {
          ensureCustomerRegisterIsMutable();
          customerRegister_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerRegisterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder addCustomerRegister(com.ecommerce.website.grpc.Customer.CustomerRegister value) {
        if (customerRegisterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerRegisterIsMutable();
          customerRegister_.add(value);
          onChanged();
        } else {
          customerRegisterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder addCustomerRegister(
          int index, com.ecommerce.website.grpc.Customer.CustomerRegister value) {
        if (customerRegisterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerRegisterIsMutable();
          customerRegister_.add(index, value);
          onChanged();
        } else {
          customerRegisterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder addCustomerRegister(
          com.ecommerce.website.grpc.Customer.CustomerRegister.Builder builderForValue) {
        if (customerRegisterBuilder_ == null) {
          ensureCustomerRegisterIsMutable();
          customerRegister_.add(builderForValue.build());
          onChanged();
        } else {
          customerRegisterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder addCustomerRegister(
          int index, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder builderForValue) {
        if (customerRegisterBuilder_ == null) {
          ensureCustomerRegisterIsMutable();
          customerRegister_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerRegisterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder addAllCustomerRegister(
          java.lang.Iterable<? extends com.ecommerce.website.grpc.Customer.CustomerRegister> values) {
        if (customerRegisterBuilder_ == null) {
          ensureCustomerRegisterIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customerRegister_);
          onChanged();
        } else {
          customerRegisterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder clearCustomerRegister() {
        if (customerRegisterBuilder_ == null) {
          customerRegister_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customerRegisterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public Builder removeCustomerRegister(int index) {
        if (customerRegisterBuilder_ == null) {
          ensureCustomerRegisterIsMutable();
          customerRegister_.remove(index);
          onChanged();
        } else {
          customerRegisterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public com.ecommerce.website.grpc.Customer.CustomerRegister.Builder getCustomerRegisterBuilder(
          int index) {
        return getCustomerRegisterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder getCustomerRegisterOrBuilder(
          int index) {
        if (customerRegisterBuilder_ == null) {
          return customerRegister_.get(index);  } else {
          return customerRegisterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public java.util.List<? extends com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder> 
           getCustomerRegisterOrBuilderList() {
        if (customerRegisterBuilder_ != null) {
          return customerRegisterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customerRegister_);
        }
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public com.ecommerce.website.grpc.Customer.CustomerRegister.Builder addCustomerRegisterBuilder() {
        return getCustomerRegisterFieldBuilder().addBuilder(
            com.ecommerce.website.grpc.Customer.CustomerRegister.getDefaultInstance());
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public com.ecommerce.website.grpc.Customer.CustomerRegister.Builder addCustomerRegisterBuilder(
          int index) {
        return getCustomerRegisterFieldBuilder().addBuilder(
            index, com.ecommerce.website.grpc.Customer.CustomerRegister.getDefaultInstance());
      }
      /**
       * <code>repeated .CustomerRegister customerRegister = 1;</code>
       */
      public java.util.List<com.ecommerce.website.grpc.Customer.CustomerRegister.Builder> 
           getCustomerRegisterBuilderList() {
        return getCustomerRegisterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ecommerce.website.grpc.Customer.CustomerRegister, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder, com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder> 
          getCustomerRegisterFieldBuilder() {
        if (customerRegisterBuilder_ == null) {
          customerRegisterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ecommerce.website.grpc.Customer.CustomerRegister, com.ecommerce.website.grpc.Customer.CustomerRegister.Builder, com.ecommerce.website.grpc.Customer.CustomerRegisterOrBuilder>(
                  customerRegister_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          customerRegister_ = null;
        }
        return customerRegisterBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CustomerRegisterResponse)
    }

    // @@protoc_insertion_point(class_scope:CustomerRegisterResponse)
    private static final com.ecommerce.website.grpc.Customer.CustomerRegisterResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ecommerce.website.grpc.Customer.CustomerRegisterResponse();
    }

    public static com.ecommerce.website.grpc.Customer.CustomerRegisterResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerRegisterResponse>
        PARSER = new com.google.protobuf.AbstractParser<CustomerRegisterResponse>() {
      @java.lang.Override
      public CustomerRegisterResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerRegisterResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerRegisterResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerRegisterResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ecommerce.website.grpc.Customer.CustomerRegisterResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerRegister_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerRegister_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerRegisterResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerRegisterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\"!\n\017CustomerRequest\022\016\n\006m" +
      "obile\030\001 \001(\003\"\215\001\n\020CustomerRegister\022\022\n\ncust" +
      "omerId\030\001 \001(\003\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastN" +
      "ame\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\016\n\006mobile\030\005 \001(\t" +
      "\022\017\n\007address\030\006 \001(\t\022\020\n\010password\030\007 \001(\t\"G\n\030C" +
      "ustomerRegisterResponse\022+\n\020customerRegis" +
      "ter\030\001 \003(\0132\021.CustomerRegister2X\n\027Customer" +
      "RegisterService\022=\n\016fetchCustomers\022\020.Cust" +
      "omerRequest\032\031.CustomerRegisterResponseB\034" +
      "\n\032com.ecommerce.website.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerRequest_descriptor,
        new java.lang.String[] { "Mobile", });
    internal_static_CustomerRegister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CustomerRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerRegister_descriptor,
        new java.lang.String[] { "CustomerId", "FirstName", "LastName", "Email", "Mobile", "Address", "Password", });
    internal_static_CustomerRegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CustomerRegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerRegisterResponse_descriptor,
        new java.lang.String[] { "CustomerRegister", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
